gs.lang.append('zhtw',[
    {key:"summary", label:"摘要 "},
    {key:"catalog", label:"目錄"},
    {key:"data", label:"資料"},
    {key:"view", label:"檢視"},

    {key:"customers", label:"顧客"},
    {key:"sell", label:"銷售"},
    {key:"item", label:"項目"},
    {key:"apply", label:"套用"},
    {key:"download", label:"下載"},
    {key:"report", label:"報告"},
    {key:"setting", label:"設定"},
    {key:"page", label:"頁面"},
    {key:"frontend", label:"檢視前台"},
    {key:"logout", label:"登出"},
    {key:"loading", label:"載入中"},
    {key:"title", label:"標題"},
    {key:"edit", label:"編輯"},
    {key:"delete", label:"刪除"},
    {key:"show", label:"顯示"},
    {key:"hide", label:"隱藏"},
    {key:"enable", label:"啟用"},
    {key:"disable", label:"停用"},
    {key:"is_reply", label:"已回覆"},
    {key:"not_reply", label:"未回"},
    {key:"email", label:"電子郵件"},
    {key:"already_read", label:"已讀"},
    {key:"unread", label:"未讀"},
    {key:"page_print", label:"列印"},
    {key:"faq_create_record", label:"新增問與答"},
    {key:"page_menu_manage", label:"頁面選單維護"},
    {key:"menu_manage_list", label:"選單維護"},
    {key:"field_menu_url", label:"網址"},
    {key:"menu_create_record", label:"新增選單"},
    {key:"link_create_record", label:"新增首頁連結項目"},
    {key:"product_category_manage", label:"商品類別管理"},
    {key:"css_create_record", label:"新增 Css 樣式"},
    {key:"css_edit_record", label:"編輯 Css 樣式"},
    {key:"guestbook", label:"留言"},

    {key:"goods_category", label:"產品分類"},
    {key:"goods_category_create", label:"新增分類"},
    {key:"goods_category_list", label:"檢視分類"},
    {key:"goods", label:"產品"},
    {key:"goods_create", label:"新增產品"},
    {key:"goods_list", label:"檢視產品"},
    {key:"device_category", label:"設備分類"},
    {key:"device_category_create", label:"新增分類"},
    {key:"device_category_list", label:"檢視分類"},
    {key:"page", label:"設備"},
    {key:"device_create", label:"新增設備"},
    {key:"device_list", label:"檢視設備"},

    {key:"field_css_title", label:"Css 樣式名稱"},
    {key:"field_css_selector", label:"選擇器(勿修改)"},
    {key:"field_css_attr", label:"屬性(勿修改)"},
    {key:"field_css_value", label:"內容值"},

    {key:"already_delete", label:"已被刪除"},
    {key:"real_delete", label:"完全刪除"},

    {key:"already_recovery", label:"記錄已還原，請重新載入列表頁"},
    {key:"recovery", label:"還原"},
    {key:"btn_close", label:"關閉"},
    {key:"view_sub_category", label:"檢視子類別"},
    {key:"view_sub_product", label:"檢視此類商品"},
    {key:"productcategory_create_record", label:"新增商品分類"},
    {key:"productcategory_edit_record", label:"編輯商品分類"},
    {key:"field_productcategory_title", label:"商品分類名稱"},
    {key:"product_create_record", label:"新增商品"},
    {key:"freight_create_record", label:"新增運費設定"},
    {key:"field_freight_start", label:"運費起始值"},
    {key:"field_freight_end", label:"運費結束值"},
    {key:"field_freight_amount", label:"金額"},
    /* 權限管理*/
    {key:"permissions_manage", label:"權限管理"},
    {key:"administrator_setting", label:"管理員"},

    {key:"data_manage", label:"其它資訊維護"},
    {key:"data_foothold", label:"加盟專區"},
    {key:"order", label:"已處理訂單"},
    {key:"order_new", label:"未處理訂單"},
    {key:"order_transform_1", label:"轉為已處理訂單"},
    {key:"order_transform_2", label:"轉為未處理訂單"},
    {key:"order_transform_3", label:"還原為未處理訂單"},
    {key:"order_list_give_up", label:"捨棄的訂單"},
    {key:"order_give_up", label:"捨棄"},
    {key:"question_report_manage", label:"問題單"},
    {key:"question_report_new", label:"問題列表"},
    {key:"question_report_done", label:"已完結的問題"},
    {key:"report_create_record", label:"回報問題"},
    {key:"report_transform_1", label:"設為已完結"},
    {key:"report_transform_2", label:"還原為一般問題"},
    {key:"report_s1", label:"已回覆"},
    {key:"report_s2", label:"等待回覆"},
    {key:"css_setting", label:"樣式設定"},


    {key:"freight", label:"運費"},
    {key:"freight_manage", label:"運費管理"},
    {key:"page_manage", label:"頁面區塊維護"},
    {key:"style_base", label:"基本樣式"},
    {key:"background_image_setting", label:"修飾圖片設定"},
    {key:"link_list", label:"首頁連結項目"},
    {key:"page_shop_cart_left_login", label:"購物車左側"},
    {key:"page_shop_cart_left_logout", label:"購物車左側-登入"},
    {key:"page_login_text", label:"登入頁面說明文字"},
    {key:"page_after_login", label:"登入後的頁面內容"},
    {key:"page_member_info", label:"修改會員頁面文字"},
    {key:"field_product_level", label:"分類階層"},
    {key:"field_product_category", label:"所屬分類"},
    {key:"field_product_content_in_list", label:"列表頁縮圖 / 說明"},
    {key:"field_product_content_in_page", label:"內頁商品圖片 / 說明"},



    {key:"edit_about_us", label:"關於我們"},
    {key:"product_related_functions", label:"商品相關"},
    {key:"sales_related_functions", label:"銷售相關"},

    {key:"contact_us", label:"聯絡我們"},
    {key:"contact_us_page", label:"聯絡我們上方說明"},

    {key:"guestbook_list", label:"留言內容"},
    {key:"member", label:"會員"},
    {key:"member_list", label:"會員列表"},
    {key:"edm_subscribed", label:"已定閱電子報"},
    {key:"edm_send", label:"發送電子報"},
    {key:"edm", label:"電子報"},
    {key:"administrator_create_record", label:"新增管理員帳號"},
    {key:"field_administrator_account", label:"管理員名稱"},
    {key:"field_administrator_password", label:"管理員密碼"},
    {key:"field_administrator_email", label:"管理員信箱"},
    {key:"product_edit_record", label:"編輯商品內容"},
    {key:"image_setting", label:"圖片設定"},

    {key:"news_category_manage", label:"最新消息分類"},
    {key:"news_manage", label:"最新消息"},
    {key:"news_create_record", label:"新增最新消息"},
    {key:"news_category_create_record", label:"新增最新消息分類"},
    {key:"news_edit_record", label:"編輯最新消息"},

    {key:"about_create_record", label:"新增關於我們"},
    {key:"about_edit_record", label:"編輯"},

    {key:"product", label:"商品"},
    {key:"product_manage", label:"商品管理"},
    {key:"product_category", label:"商品類別"},
    {key:"product_category_manage", label:"商品類別管理"},
    {key:"ourstore_category_manage", label:"加盟商家列表"},
    {key:"banner_manage", label:"橫幅輪撥圖片"},

    {key:"notice", label:"通知"},
    {key:"theme", label:"樣式"},
    {key:"uiLoader.complete", label:"即將完成"},
    {key:"uiLoader.buildProgressBar", label:"正在建立載入清單"},

    {key:"interactive", label:"互動"},

    {key:"field_news_type", label:"類型"},
    {key:"field_icon_plus", label:"+"},
    {key:"upload_image", label:"上傳圖片"},
    {key:"image_remove", label:"移除圖片"},
    {key:"field_product_images", label:"內頁商品圖片"},

    {key:"newsletter_create_record", label:"新增電子報記錄"},
    {key:"field_newsletter_title", label:"電子信箱"},
    {key:"edm_list", label:"電子報訂閱列表"},
    {key:"newsletter_sender", label:"發送電子報"},

    /* 問與答 */
    {key:"faq_manage", label:"問與答"},
    {key:"faq_category_manage", label:"問與答分類"},
    {key:"faq_manage", label:"問與答"},
    {key:"faq_create_record", label:"新增問與答"},
    {key:"faq_category_create_record", label:"新增問與答分類"},
    {key:"faq_edit_record", label:"編輯問與答"},
    
    {key:"field_sitep_name", label:"頁面名稱"},
    {key:"page_terms", label:"使用條款與須知"},
    /* 圖片 */
    {key:"page_manage_list", label:"網站頁面維護"},
    {key:"field_sitep_name", label:"頁面名稱"},
    {key:"page_terms", label:"使用條款與須知"},
    {key:"page_footer", label:"頁尾"},
    {key:"page_footer_2", label:"頁腳"},
    {key:"page_privacypolicy", label:"隱私權保護政策"},
    {key:"page_sitemap", label:"網站地圖"},
    {key:"page_edit", label:"內容維護"},
    {key:"system_page", label:"系統頁面"},
    {key:"page_menuindex", label:"首頁左側區塊"},
    {key:"page_menuinpage", label:"內頁選單下方區塊"},
    {key:"sitep_create_record", label:"新增頁面"},

    /* 頁面標題圖片 */
    {key:"ptitle_image_setting", label:"標題圖片設定"},
    {key:"ptitle_create_record", label:"新增圖片"},
    {key:"ptitle_edit_record", label:"編輯圖片"},
    {key:"field_ptitle_title", label:"圖片名稱"},
    {key:"field_ptitle_jq_selector", label:"jQuery 選擇器"},
    {key:"field_ptitle_image", label:"圖片"},
    /* 頁面圖片 */
    {key:"pimg_image_setting", label:"頁面圖片設定"},
    {key:"pimg_create_record", label:"新增圖片"},
    {key:"pimg_edit_record", label:"編輯圖片"},
    {key:"field_pimg_title", label:"圖片名稱"},
    {key:"field_pimg_jq_selector", label:"jQuery 選擇器"},
    {key:"field_pimg_image", label:"圖片"},
    /* 修飾圖 */
    {key:"reset", label:"重置"},
    {key:"background_create_record", label:"新增修飾圖"},
    {key:"background_edit_record", label:"編輯修飾圖"},
    {key:"field_background_title", label:"修飾圖名稱"},
    {key:"field_background_jq_selector", label:"jQuery 選擇器"},
    {key:"field_background_image", label:"修飾圖"},
    /* 商品*/
    {key:"field_product_no", label:"編號"},
    {key:"field_product_low", label:"庫存數量"},
    {key:"field_product_efficacy", label:"功效說明"},
    {key:"field_product_price", label:"售價"},
    {key:"field_product_use_method", label:"使用方法"},
    {key:"field_product_components", label:"主要成份"},
    {key:"field_is_allowed_to_buy", label:"是否可以允許購買"},
    {key:"field_allowed_to_buy", label:"允許購買"},
    {key:"field_not_allowed_to_buy", label:"不允許購買"},
    {key:"field_product_image", label:"列表頁縮圖"},
    /* 聯絡我們*/
    {key:"field_contact_name", label:"聯絡人"},
    {key:"field_contact_address", label:"聯絡地址"},
    {key:"field_contact_telephone", label:"聯絡電話"},
    {key:"field_contact_email", label:"聯絡信箱"},
    {key:"field_contact_remark", label:"諮詢內容"},
    {key:"contact_view_record", label:"檢視聯絡我們內容"},
    /* 橫幅圖片*/
    {key:"banner_create_record", label:"新增橫幅圖片"},
    {key:"banner_edit_record", label:"編輯橫幅圖片"},
    {key:"field_banner_title", label:"標題"},
    {key:"field_banner_image", label:"圖片"},
    /* 合作廠商*/
    {key:"partners_manage", label:"合作廠商"},
    {key:"partners_create_record", label:"新增合作廠商"},
    {key:"partners_edit_record", label:"編輯合作廠商"},
    {key:"field_partners_title", label:"標題"},
    {key:"field_partners_site_url", label:"網址"},
    {key:"field_partners_image", label:"圖片"},
    /* 會員*/
    {key:"member_create_record", label:"新增會員資料"},
    {key:"member_edit_record", label:"編輯會員資料"},
    {key:"field_member_account", label:"帳號"},
    {key:"field_member_password", label:"密碼"},
    {key:"field_member_name", label:"姓名"},
    {key:"field_member_sex", label:"性別"},
    {key:"field_member_telephone", label:"電話"},
    {key:"field_member_mobile", label:"手機"},
    {key:"field_member_address", label:"地址"},
    {key:"field_member_remark", label:"備註"},
    {key:"field_member_birthday", label:"生日"},
    /* 世界各國*/
    {key:"menu_country", label:"國家列表"},
    {key:"field_country_title", label:"國家名稱"},
    {key:"field_country_code", label:"國家代碼"},
    {key:"country_create_record", label:"新增國家資訊"},
    {key:"country_edit_record", label:"編輯國家資訊"},
    /* 門市據點*/
    {key:"foothold_create_record", label:"新增門市據點"},
    {key:"foothold_edit_record", label:"編輯門市據點"},
    {key:"field_foothold_title", label:"據點名稱"},
    {key:"field_foothold_category", label:"所在國家"},
    {key:"field_foothold_telephone", label:"服務電話"},
    {key:"field_foothold_address", label:"服務地址"},
    {key:"field_foothold_time", label:"營業時間"},
    {key:"field_foothold_desc", label:"簡短描述"},
    {key:"field_foothold_image", label:"據點圖片"},
    /* 人材召募*/
    {key:"jobs_create_record", label:"新增工作職缺"},
    {key:"jobs_edit_record", label:"編輯工作職缺"},
    {key:"field_demand_people", label:"需求人數"},
    {key:"field_job_location", label:"工作地點"},
    {key:"field_job_conditions", label:"職位條件"},
    {key:"field_work_content", label:"工作內容"},
    {key:"field_job_department", label:"部門"},
    {key:"field_public_date", label:"發佈日期"},
    {key:"our_jobs_related_functions", label:"人材招募"},
    {key:"our_jobs_list", label:"工作列表"},
    {key:"job_seekers", label:"應徵人員"},
    {key:"field_job_link_title", label:"相關連結標題"},
    {key:"field_job_link_url", label:"相關連結網址"},
    {key:"btn_public_job", label:"發佈"},
    {key:"btn_stop_job", label:"停止"},
    /* 語系設定*/
    {key:"current_language", label:"繁體中文"},
    {key:"language_zhtw", label:"繁體中文"},
    {key:"language_zhcn", label:"简体中文"},
    {key:"language_enus", label:"englisth"},
    {key:"language_jpjp", label:"日本語"},
    {key:"language_setting", label:"語系設定"},
    /* 表單欄位*/
    {key:"field_title", label:"標題"},
    {key:"field_content", label:"內容"},
    {key:"field_submit", label:"送出"},
    {key:"field_cancel", label:"取消"},
    {key:"field_save", label:"儲存"},
    /* 系統訊息 */
    {key:"init_menu", label:"初始化選單"},
    {key:"init_page", label:"初始化頁面"},
    {key:"500 internal server error", label:"伺服器發生錯誤了"},
    {key:"404 Not Found", label:"頁面不存在"},
    {key:"null", label:""}
]);